services:
  postgres:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_USER: ${GOT_DB_USER}
      POSTGRES_PASSWORD: ${GOT_DB_PASS}
      POSTGRES_DB: ${GOT_DB_NAME}
    ports:
      - "${GOT_DB_PORT}:${GOT_DB_PORT}"
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - ./db/migrations/001_init.sql:/docker-entrypoint-initdb.d/initdb.sql

  nats:
    image: nats:2.10.26-alpine3.21
    ports:
      - "${GOT_NATS_PORT}:${GOT_NATS_PORT}"
    networks:
      - app-network
    env_file:
      - .env

  app:
    container_name: gotemplate
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
      - nats
    networks:
      - app-network
    ports:
      - "${GOT_APP_PORT}:${GOT_APP_PORT}"
    env_file:
      - .env

networks:
  app-network:
