services:
  postgres:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - ./db/migrations/001_init.sql:/docker-entrypoint-initdb.d/initdb.sql

  nats:
    image: nats:2.10.26-alpine3.21
    ports:
      - "${NATS_PORT}:${NATS_PORT}"
    networks:
      - app-network
    env_file:
      - .env

  app:
    container_name: gotemplate
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
      - nats
    networks:
      - app-network
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env

networks:
  app-network:
