services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network
    env_file:
      - .env

  nats:
    image: nats:2.10.26
    networks:
      - app-network

  app:
    container_name: gotemplate
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
      - nats
    networks:
      - app-network
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env

volumes:
  postgres-data:

networks:
  app-network:
