package config

const (
	DB_PORT_KEY = "DB_PORT",
	DB_USER_KEY = "DB_USER",
	DB_PASSWORD_KEY = "DB_PASSWORD",
	DB_NAME_KEY = "DB_NAME",

	NATS_PORT_KEY = "NATS_PORT",
	NATS_MONITOR_PORT_KEY = "NATS_MONITOR_PORT"

	APP_PORT_KEY = "APP_PORT"
)